[package]
name = "solver_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.69"
js-sys = { version = "0.3.61", default-features = false }
trout = { path = "../.." }
wasm-bindgen = "0.2.84"

console_error_panic_hook = "0.1"